name: intertech
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.8.1
  cupertino_icons: ^1.0.2
  mobx: ^2.2.3
  http: ^1.1.0
  dio: ^5.4.0
  build_runner: ^2.4.7
  flutter_mobx: ^2.2.0+1
  carousel_slider: ^4.2.1
  shimmer: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  mobx_codegen: ^2.4.0

  flutter_lints: ^3.0.1


flutter:


  uses-material-design: true
